### PR TITLE
More pretty messages and content container.

### PR DESCRIPTION
**Pull request by mira-ta**
## Messages fixes
Major messages ui fixes like deleting borders, recalculated margins and etc. In short, there are images to see the differences. By the point, now content container *fits* the entire height (actually no, it's an image attached to `body` background)

Also a thin orange *webkit-only* scrollbar was added, it looks pretty enough for the *dark and orange* style (it is not on images)

**How it was**

How it was before

**How it is now**

How it is now

### CODE REVIEW

**Comment by mira-ta** [comment]
I am thinking about the thing that this pull request is forgotten x(

**Comment by iamdiogo** [comment]
Thank you for your contribution! I'll review this at the end of this week as it is when I'm more available to do so.

**Comment by mira-ta** [comment]
By the way.

I have a branch called `restructure`, which is default branch in my fork. I have changed some things there, like, css file is now formatted, some fixes, some features.

Can you consider checking that branch? Maybe, I'll pull request, or I will commit them as different commit in `master` branch?

**Comment by iamdiogo** [comment]
Hello @mira-ta . Sorry for my late response, college has been crazy lately.

I've seen your changes, and although I did like some additions you've made to the README description, there are some things you should leave for me to update. I'm talking about the changelog, for example.

Then, in the actual styling, I saw you updated the body's background to a base64 image. Once again, that wasn't a change that needed to be done, as it's working fine.
In terms of the new messaging styling you've made, I felt it could hurt accessibility, but I understood what you were going for, so we might look into updating some styles.

I'm sure you were always well intended, and it's clear to me that you have a big will to make contributions, I respect that. I'm sorry I didn't accept your changes to the project, but this pull request was "too widespread" in terms of quantity of changes that even if I agreed with some changes, I couldn't accept it because of rejecting others.

For the future, just make small, "non-intrusive", change increments, and keep them separated in different pull requests. I hope this doesn't make you hesitant of contributing the next time, as you seem to be a nice well-meant person.

For what it's worth, you reminded me to create a CONTRIBUTING file so that this doesn't happen to others.
Thank you :slightly_smiling_face:

**Pull request closed without merging**
